const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),vm=require('node:vm'),os=require('node:os'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),moduleFile=path.join(root,'electron/game/clientmod.js');
const sum=value=>crypto.createHash('sha256').update(value).digest('hex');
async function fixture(t,remote=null){
 const temp=await fs.mkdtemp(path.join(os.tmpdir(),'monkey-mod-v5-'));t.after(()=>fs.rm(temp,{recursive:true,force:true}));
 const bundle=path.join(temp,'bundled');await fs.mkdir(bundle,{recursive:true});
 const releases=['fabric','forge'].flatMap(loader=>['26.2','1.21.11'].map(minecraft=>({version:'0.5.0',loader,minecraft,file:`monkey-${minecraft}-${loader}.jar`,sha256:sum(`${minecraft}-${loader}`)})));
 for(const r of releases)await fs.writeFile(path.join(bundle,r.file),`${r.minecraft}-${r.loader}`);await fs.writeFile(path.join(bundle,'monkeyclient.json'),JSON.stringify({releases}));
 const downloads=[],io={fsp:fs,instance:id=>path.join(temp,id),ensureDir:d=>fs.mkdir(d,{recursive:true}),download:async(url,file)=>{downloads.push(url);await fs.writeFile(file,'remote');}};
 const context={module:{exports:{}},__dirname:path.join(temp,'electron/game'),AbortSignal,require:name=>name==='./io'?io:name==='../config'?{clientModRepo:'test/fixture'}:require(name),fetch:async url=>{if(remote===null)throw Error('offline');return {ok:true,json:async()=>url.endsWith('/releases/latest')?{assets:[{name:'monkeyclient.json',browser_download_url:'https://fixture/catalog'},{name:'new.jar',browser_download_url:'https://fixture/new.jar',size:6}]}:{releases:[{version:remote,minecraft:'26.2',loader:'fabric',file:'new.jar',sha256:sum('remote')}]}};}};
 vm.runInNewContext(await fs.readFile(moduleFile,'utf8'),context,{filename:moduleFile});return {api:context.module.exports,profile:{id:'test',loader:'fabric',version:'26.2',mods:[{projectId:'P7dR8mSH'}]},dir:path.join(temp,'test/mods'),bundle,downloads};
}
test('offline installs the exact bundled game and loader build',async t=>{const f=await fixture(t);assert.equal((await f.api.ensure(f.profile)).installed,'0.5.0');assert.equal(await fs.readFile(path.join(f.dir,'monkeyclient.jar'),'utf8'),'26.2-fabric');});
test('Forge installs its own artifact without Fabric API',async t=>{const f=await fixture(t);f.profile.loader='forge';f.profile.mods=[];assert.equal((await f.api.ensure(f.profile)).installed,'0.5.0');assert.equal(await fs.readFile(path.join(f.dir,'monkeyclient.jar'),'utf8'),'26.2-forge');assert.equal(f.downloads.length,0);});
test('changing Minecraft installs the corresponding artifact even at the same mod version',async t=>{const f=await fixture(t);await f.api.ensure(f.profile);f.profile.version='1.21.11';assert.equal((await f.api.ensure(f.profile)).installed,'0.5.0');assert.equal(await fs.readFile(path.join(f.dir,'monkeyclient.jar'),'utf8'),'1.21.11-fabric');});
test('same verified version stays in place',async t=>{const f=await fixture(t);await f.api.ensure(f.profile);assert.equal((await f.api.ensure(f.profile)).current,'0.5.0');});
test('newer compatible published release wins',async t=>{const f=await fixture(t,'0.5.1');assert.equal((await f.api.ensure(f.profile)).installed,'0.5.1');assert.equal(f.downloads.length,1);});
test('older published release cannot downgrade the bundle',async t=>{const f=await fixture(t,'0.4.0');assert.equal((await f.api.ensure(f.profile)).installed,'0.5.0');assert.equal(f.downloads.length,0);});
test('newer verified installed build is preserved offline',async t=>{const f=await fixture(t);await fs.mkdir(f.dir,{recursive:true});await fs.writeFile(path.join(f.dir,'monkeyclient.jar'),'newer');await fs.writeFile(path.join(f.dir,'monkeyclient-version.json'),JSON.stringify({version:'0.5.2',minecraft:'26.2',loader:'fabric',sha256:sum('newer')}));assert.equal((await f.api.ensure(f.profile)).kept,'0.5.2');});
test('unknown game combinations fail without installing another version',async t=>{const f=await fixture(t);f.profile.version='1.20.1';await assert.rejects(f.api.ensure(f.profile),/No compatible/);await assert.rejects(fs.stat(path.join(f.dir,'monkeyclient.jar')));});
test('corrupted bundle cannot be installed',async t=>{const f=await fixture(t);await fs.writeFile(path.join(f.bundle,'monkey-26.2-fabric.jar'),'tampered');await assert.rejects(f.api.ensure(f.profile),/No compatible/);});
test('corrupted installed artifact is repaired',async t=>{const f=await fixture(t);await f.api.ensure(f.profile);await fs.writeFile(path.join(f.dir,'monkeyclient.jar'),'tampered');assert.equal((await f.api.ensure(f.profile)).installed,'0.5.0');});
test('disabling the integrated mod preserves its file outside loader scanning',async t=>{const f=await fixture(t);await f.api.ensure(f.profile);f.profile.settings={clientMod:false};assert.ok((await f.api.ensure(f.profile)).skipped);assert.equal(await fs.readFile(path.join(f.dir,'monkeyclient.jar.disabled'),'utf8'),'26.2-fabric');});
test('vanilla profile does not install a mod',async t=>{const f=await fixture(t);f.profile.loader='vanilla';assert.ok((await f.api.ensure(f.profile)).skipped);});
test('release catalog contains every supported modded combination with matching hashes',async()=>{const catalog=JSON.parse(await fs.readFile(path.join(root,'bundled/monkeyclient.json')));assert.equal(catalog.releases.length,15);const keys=new Set();for(const r of catalog.releases){assert.equal(sum(await fs.readFile(path.join(root,'bundled',r.file))),r.sha256);keys.add(r.minecraft+':'+r.loader);}assert.equal(keys.size,15);assert.ok(!keys.has('26.3:forge'));});
