const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),{EventEmitter}=require('node:events');
const PNG=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jFZkAAAAASUVORK5CYII=','base64');
test('Microsoft direct login uses unique state and PKCE and rejects mismatched callbacks',()=>{
 const auth=require('../electron/browser-auth'),r=auth.request('fixture'),url=new URL(r.url);assert.equal(url.searchParams.get('code_challenge_method'),'S256');assert.equal(url.searchParams.get('code_challenge'),crypto.createHash('sha256').update(r.verifier).digest('base64url'));assert.notEqual(auth.request('fixture').state,r.state);assert.equal(auth.response(auth.REDIRECT+'?state='+r.state+'&code=good',r.state),'good');assert.throws(()=>auth.response(auth.REDIRECT+'?state=wrong&code=bad',r.state),/state/);assert.equal(auth.response('https://example.com/?code=bad',r.state),null);
});
test('archived screenshots survive removed profiles and deleted images do not return',async t=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'monkey-gallery-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));let profiles=[{id:'one',name:'First'},{id:'two',name:'Second'}];
 for(const p of profiles){const dir=path.join(root,'instances',p.id,'screenshots');await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,'same.png'),PNG);await fs.writeFile(path.join(dir,'partial.png'),PNG.subarray(0,32));}
 const {createScreenshotService}=require('../electron/screenshots');const options={store:{loadData:async()=>({profiles})},io:{root:()=>root,instance:id=>path.join(root,'instances',id)},nativeImage:{createThumbnailFromPath:async()=>({toJPEG:()=>Buffer.from('thumb')})},shell:{}};let service=createScreenshotService(options),list=await service.list();assert.equal(list.total,2);const removed=list.items.find(s=>s.profileId==='one');await service.remove(removed.id);assert.equal((await service.list()).total,1);profiles=[];await fs.rm(path.join(root,'instances'),{recursive:true});service=createScreenshotService(options);assert.equal((await service.list()).total,1);
});
test('dependency resolution is recursive, exact-version and avoids bundled loader APIs',async()=>{
 const {resolve}=require('../electron/game/dependencies'),profile={version:'26.2',loader:'fabric',mods:[],settings:{performance:'off'}};
 const version=(id,deps=[])=>({id,project_id:id,game_versions:['26.2'],loaders:['fabric'],dependencies:deps,version_number:'1',files:[{primary:true,filename:id+'.jar',url:'https://cdn.modrinth.com/'+id,hashes:{sha1:'a'.repeat(40)}}]});
 const versions={dep:version('dep',[{dependency_type:'required',version_id:'child'}]),child:version('child')};
 const fetch=async url=>({ok:true,json:async()=>url.includes('/version/')?versions[url.split('/').pop()]:{title:url.split('/').pop()}});
 const rows=await resolve(profile,version('root',[{dependency_type:'required',project_id:'P7dR8mSH'},{dependency_type:'required',version_id:'dep'}]),fetch);assert.deepEqual(rows.map(r=>r.projectId),['child','dep']);versions.child.game_versions=['1.21.9'];await assert.rejects(resolve(profile,version('root',[{dependency_type:'required',version_id:'child'}]),fetch),/compatible/);
});
test('in-game bridge requires per-session token, rejects web origins and limits inputs',async t=>{
 const events=[];class Window{constructor(){this.dead=false;this.webContents=new EventEmitter();Object.assign(this.webContents,{setFrameRate:()=>{},setWindowOpenHandler:()=>{},startPainting:()=>{},stopPainting:()=>{},isDestroyed:()=>false,sendInputEvent:e=>events.push(e),insertText:text=>events.push(text)});}async loadFile(){this.webContents.emit('paint',null,null,{toPNG:()=>Buffer.from('png-fixture')});}isDestroyed(){return this.dead;}destroy(){this.dead=true;}}
 const bridge=require('../electron/game-ui').createGameUI({BrowserWindow:Window,net:{}});t.after(()=>bridge.close());const env=await bridge.session('fixture'),url=env.MONKEY_UI_URL,headers={Authorization:'Bearer '+env.MONKEY_UI_TOKEN,'Content-Type':'application/json'};
 assert.equal((await fetch(url+'/frame')).status,401);assert.equal((await fetch(url+'/frame',{headers:{...headers,Origin:'https://example.com'}})).status,401);
 const post=(route,b)=>fetch(url+route,{method:'POST',headers,body:JSON.stringify(b)});assert.equal((await post('/open',{tab:'play'})).status,400);assert.equal((await post('/open',{tab:'friends'})).status,200);assert.equal(await (await fetch(url+'/frame',{headers})).text(),'png-fixture');assert.equal((await post('/input',{type:'eval',text:'bad'})).status,400);await post('/input',{type:'mouseDown',x:2000,y:-10});assert.equal(events[0].x,999);assert.equal(events[0].y,0);bridge.release('fixture');assert.equal((await fetch(url+'/frame',{headers})).status,401);
});
